# Generated by Django 5.1.7 on 2025-04-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='credit_rating',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
